### ISSUE TITLE
@@@@@@@

### ISSUE THREAD

**Issue by lonycc** [tonyxyl/docs#1]

**Comment by tonyxyl** [comment]
[vue-element-admin](https://github.com/PanJiaChen/vue-element-admin)
[laravel-vue-admin](https://github.com/vueadmin/VueAdmin)

**Comment by tonyxyl** [comment]
[php windows](http://windows.php.net/downloads/pecl/releases/)
[pecl](http://pecl.php.net/package-stats.php)

[flask celery](http://blog.csdn.net/jmilk/article/details/53677411)
[flask-jwt](http://www.thatyou.cn/flask-flask-jwt-%E5%AE%9E%E7%8E%B0%E5%9F%BA%E4%BA%8Ejson-web-token%E7%9A%84%E7%94%A8%E6%88%B7%E8%AE%A4%E8%AF%81%E6%8E%88%E6%9D%83/)


[python with](https://www.ibm.com/developerworks/cn/opensource/os-cn-pythonwith/)

[web analytics data collection](http://blog.codinglabs.org/articles/how-web-analytics-data-collection-system-work.html)

[content security policies](http://cspisawesome.com/content_security_policies)
[awesomes web](https://www.awesomes.cn/)
[mean.io](http://mean.io/)
[Apktool](https://ibotpeaches.github.io/Apktool/install/)


[linuxidc](http://linux.linuxidc.com/)

[perl](http://www.cpan.org/src/)

[amazing windows apps](https://amazing-apps.gitbooks.io/windows-apps-that-amaze-us/content/zh-CN/)



**无聊**
[windows93风格的网站](http://www.windows93.net/)
[dns解析日志](http://202.38.64.1/dns/)
[未来世界,阮一峰的文章](http://survivor.ruanyifeng.com/)
[cmd风格的电台](http://cmd.to/fm)
[看剧](https://tv.now.sh/top)
[网文](http://book.16808.cn/)


[Docker环境搭建ZooKeeper集群](http://www.jianshu.com/p/14d30aa63dc9)
[使用 Docker 一步搞定 ZooKeeper 集群的搭建](https://segmentfault.com/a/1190000006907443)
[通过docker swarm搭建ELK集群](http://www.jianshu.com/p/930917d05b63)
[Docker Swarm架构、特性与基本实践](http://www.jianshu.com/p/6f9f9183f981)
[邓白氏编码申请](http://www.jianshu.com/p/8539f0d2b2f0)
[openstack pike部署](https://www.jianshu.com/p/c5387c8d0f4f)
[KVM的原理与使用](https://www.jianshu.com/p/03d3afff3b5f)
[python redis](http://www.cnblogs.com/melonjiang/p/5342505.html)
[graphql](http://facebook.github.io/graphql/October2016/#sec-Overview)
[apijson](https://my.oschina.net/tommylemon/blog/805459)
[docker构建laravel开发环境](https://segmentfault.com/a/1190000007873815)

[区块链入门资料](https://bitshuo.com/topic/583405978bf98a143753b86a)

[抓到一个sql注入点](http://www.xiazaizhijia.com/api.php?op=ballot&id=1&modelid=1&radio=)
[Redis统计在线用户数](http://www.open-open.com/lib/view/open1471683474268.html)
[值得关注的官方API](https://segmentfault.com/a/1190000008149811)

[pyredis用法举例](http://debugo.com/python-redis/)

[chrome调试工具介绍](https://segmentfault.com/a/1190000002439648)
[广州小汽车摇号公示](http://apply.gzjt.gov.cn/apply/norm/personQuery.html)

**Comment by tonyxyl** [comment]
**解决一个问题**
[web访问日志收集](http://blog.codinglabs.org/articles/how-web-analytics-data-collection-system-work.html)
[Docker环境搭建ZooKeeper集群](http://www.jianshu.com/p/14d30aa63dc9)
[使用 Docker 一步搞定 ZooKeeper 集群的搭建](https://segmentfault.com/a/1190000006907443)
[通过docker swarm搭建ELK集群](http://www.jianshu.com/p/930917d05b63)
[Docker Swarm架构、特性与基本实践](http://www.jianshu.com/p/6f9f9183f981)
[邓白氏编码申请](http://www.jianshu.com/p/8539f0d2b2f0)
[openstack pike部署](https://www.jianshu.com/p/c5387c8d0f4f)
[KVM的原理与使用](https://www.jianshu.com/p/03d3afff3b5f)
[python redis](http://www.cnblogs.com/melonjiang/p/5342505.html)
[docker构建laravel开发环境](https://segmentfault.com/a/1190000007873815)
[区块链入门资料](https://bitshuo.com/topic/583405978bf98a143753b86a)
[抓到一个sql注入点](http://www.xiazaizhijia.com/api.php?op=ballot&id=1&modelid=1&radio=)
[Redis统计在线用户数](http://www.open-open.com/lib/view/open1471683474268.html)
[值得关注的官方API](https://segmentfault.com/a/1190000008149811)
[pyredis用法举例](http://debugo.com/python-redis/)
[chrome调试工具介绍](https://segmentfault.com/a/1190000002439648)
[python with用法介绍](https://www.ibm.com/developerworks/cn/opensource/os-cn-pythonwith/)
[flask celery使用demo](http://blog.csdn.net/jmilk/article/details/53677411)
